"""Entry porch (vestibule) generator.

User intent:
- Door starts at belt plane (z = belt height).
- Porch projects outward from the dome by up to 0.5m.
- Frame members are 45mm x 45mm (configurable).
- Porch is glazed (simple glass panels in each face), and door leaf is framed/glazed.

The porch is structurally connected to the dome via bracket plates at the
dome-side posts.  The brackets align to the actual belt-edge strut endpoints
closest to the porch, ensuring a real load path between porch and dome.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any, Optional, Tuple, List

from .parameters import DomeParameters
from .tessellation import TessellatedDome

__all__ = ["EntryPorchResult", "EntryPorchBuilder"]


@dataclass(slots=True)
class EntryPorchResult:
    name: str
    angle_deg: float
    belt_height_m: float
    bracket_node_indices: List[int] = field(default_factory=list)  # dome node indices the porch connects to


class EntryPorchBuilder:
    def __init__(self, params: DomeParameters):
        self.params = params
        self._doc: Optional[Any] = None
        self._fc_unit_scale: float = 1000.0

    @property
    def document(self) -> Optional[Any]:
        return self._doc

    def _fc_len(self, meters: float) -> float:
        return float(meters) * float(self._fc_unit_scale)

    def ensure_document(self) -> Optional[Any]:
        try:
            import FreeCAD  # type: ignore
        except ImportError:  # pragma: no cover
            return None
        doc = FreeCAD.ActiveDocument
        if doc is None:
            doc = FreeCAD.newDocument("GeodesicDome")
        return doc

    # ------------------------------------------------------------------
    # Belt-node helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _belt_node_indices(
        dome: TessellatedDome,
        belt_height: float,
        tolerance: float = 0.02,
    ) -> List[int]:
        """Return node indices on the belt plane."""
        return [
            i for i, n in enumerate(dome.nodes)
            if abs(n[2] - belt_height) <= tolerance
        ]

    @staticmethod
    def _nearest_belt_nodes(
        dome: TessellatedDome,
        belt_indices: List[int],
        target_x: float,
        target_y: float,
        count: int = 2,
    ) -> List[int]:
        """Find *count* belt nodes closest to the (x, y) porch attachment."""
        scored = []
        for idx in belt_indices:
            nx, ny, _nz = dome.nodes[idx]
            dist = math.hypot(nx - target_x, ny - target_y)
            scored.append((dist, idx))
        scored.sort()
        return [idx for _d, idx in scored[:count]]

    # ------------------------------------------------------------------
    # Main entry
    # ------------------------------------------------------------------

    def create_entry_porch(self, dome: TessellatedDome) -> EntryPorchResult | None:
        if not self.params.generate_entry_porch:
            return None

        doc = self.ensure_document()
        self._doc = doc
        if doc is None:
            return None

        try:
            import FreeCAD  # type: ignore
            import Part  # type: ignore
            from FreeCAD import Vector  # type: ignore
        except Exception:  # pragma: no cover
            return None

        R = float(self.params.radius_m)
        hemi = float(self.params.hemisphere_ratio)
        if hemi >= 0.999999:
            # Porch assumes a belt opening.
            return None

        belt_height_m = R * (1.0 - 2.0 * hemi)
        disc = R * R - belt_height_m * belt_height_m
        if disc <= 1e-12:
            return None
        belt_radius_m = float(math.sqrt(disc))

        depth_m = float(self.params.porch_depth_m)
        depth_m = min(depth_m, 0.5)
        width_m = float(self.params.porch_width_m)
        height_m = float(self.params.porch_height_m)
        member_m = float(self.params.porch_member_size_m)
        glass_m = float(self.params.porch_glass_thickness_m)

        door_w = float(self.params.door_width_m)
        door_h = float(self.params.door_height_m)
        clearance = float(self.params.door_clearance_m)

        # Angle: either manual or auto-derived from dome.
        ang_deg = float(self.params.door_angle_deg)
        ang_rad = math.radians(ang_deg)

        # Local porch coordinate system:
        # X = outward radial, Y = tangential, Z = up.
        # Origin is at the belt plane centerline on the dome surface.
        # We model everything in local coords then rotate+translate.

        x0 = self._fc_len(belt_radius_m)
        z0 = self._fc_len(belt_height_m)

        # Frame outer extents.
        depth = self._fc_len(depth_m)
        width = self._fc_len(width_m)
        height = self._fc_len(height_m)
        msz = self._fc_len(member_m)

        # Convenience: make a 45x45 member along local X/Y/Z.
        def member_box(len_x: float, len_y: float, len_z: float, px: float, py: float, pz: float):
            b = Part.makeBox(len_x, len_y, len_z)
            b.Placement = FreeCAD.Placement(Vector(px, py, pz), FreeCAD.Rotation())
            return b

        solids: List[Any] = []

        # Outer rectangular frame (4 sides) at the porch front plane (x = belt_radius + depth).
        # We build it as posts/rails with thickness msz.
        front_x = x0 + depth
        half_w = width / 2.0

        # Two vertical posts (left/right)
        solids.append(member_box(msz, msz, height, front_x - msz, -half_w, z0))
        solids.append(member_box(msz, msz, height, front_x - msz, half_w - msz, z0))
        # Top rail
        solids.append(member_box(msz, width, msz, front_x - msz, -half_w, z0 + height - msz))
        # Bottom rail (sits at belt plane)
        solids.append(member_box(msz, width, msz, front_x - msz, -half_w, z0))

        # Side returns (connect front to dome) â€“ left/right and top.
        # Left side: a horizontal rail from dome surface to front.
        solids.append(member_box(depth, msz, msz, x0, -half_w, z0 + height - msz))  # top-left return
        solids.append(member_box(depth, msz, msz, x0, -half_w, z0))  # bottom-left return
        solids.append(member_box(depth, msz, msz, x0, half_w - msz, z0 + height - msz))  # top-right return
        solids.append(member_box(depth, msz, msz, x0, half_w - msz, z0))  # bottom-right return
        # Two vertical side posts near dome surface (optional stiffener)
        solids.append(member_box(msz, msz, height, x0, -half_w, z0))
        solids.append(member_box(msz, msz, height, x0, half_w - msz, z0))

        # Top return across width near dome surface.
        solids.append(member_box(msz, width, msz, x0, -half_w, z0 + height - msz))

        # ---------------------------------------------------------------
        # Structural brackets connecting porch posts to dome belt nodes.
        # For each dome-side post find the nearest belt node and create
        # an L-bracket plate that ties the porch member to that node.
        # ---------------------------------------------------------------
        belt_tol = max(0.02, R * 0.01)  # tolerance for belt node detection
        belt_indices = self._belt_node_indices(dome, belt_height_m, belt_tol)
        bracket_node_indices: List[int] = []

        if belt_indices:
            bracket_thickness_mm = max(msz * 0.15, self._fc_len(0.003))
            bracket_leg_mm = msz * 2.5  # L-bracket leg length

            # Left and right post attachment points (local coords, pre-rotation)
            post_locals = [
                (belt_radius_m, -width_m / 2.0),   # left
                (belt_radius_m, width_m / 2.0),     # right
            ]

            for px_m, py_m in post_locals:
                # Rotate the local attachment point to world coords.
                wx = px_m * math.cos(ang_rad) - py_m * math.sin(ang_rad)
                wy = px_m * math.sin(ang_rad) + py_m * math.cos(ang_rad)

                nearest = self._nearest_belt_nodes(dome, belt_indices, wx, wy, count=1)
                bracket_node_indices.extend(nearest)

                for ni in nearest:
                    node = dome.nodes[ni]
                    # Node position in mm.
                    ncx = node[0] * self._fc_unit_scale
                    ncy = node[1] * self._fc_unit_scale
                    ncz = node[2] * self._fc_unit_scale

                    # Radial outward direction from dome center (XY plane).
                    r_xy = math.hypot(node[0], node[1])
                    if r_xy < 1e-9:
                        continue
                    dx_r = node[0] / r_xy
                    dy_r = node[1] / r_xy

                    # Bracket: a flat plate lying radially outward, with a
                    # vertical plate lying along Z. Both are bracket_thickness
                    # thick. The L spans bracket_leg in the Z and radial directions.
                    # Horizontal plate (lies at belt Z plane, extends radially)
                    h_plate = Part.makeBox(
                        bracket_leg_mm,
                        bracket_thickness_mm,
                        bracket_thickness_mm,
                    )
                    # Place: centered on node, extend outward
                    h_base = Vector(
                        ncx - bracket_thickness_mm * 0.5 * dy_r,
                        ncy + bracket_thickness_mm * 0.5 * dx_r,
                        ncz,
                    )
                    # Align the long axis with the radial direction
                    h_angle = math.degrees(math.atan2(dy_r, dx_r))
                    h_rot = FreeCAD.Rotation(Vector(0, 0, 1), h_angle)
                    h_plate.Placement = FreeCAD.Placement(h_base, h_rot)
                    solids.append(h_plate)

                    # Vertical plate (rises from belt plane at node)
                    v_plate = Part.makeBox(
                        bracket_thickness_mm,
                        bracket_thickness_mm,
                        bracket_leg_mm,
                    )
                    v_base = Vector(
                        ncx - bracket_thickness_mm * 0.5,
                        ncy - bracket_thickness_mm * 0.5,
                        ncz,
                    )
                    v_plate.Placement = FreeCAD.Placement(v_base, FreeCAD.Rotation())
                    solids.append(v_plate)

        # Front glazing panel (simple sheet inside the front frame).
        if glass_m > 1e-6:
            gth = self._fc_len(glass_m)
            inset = msz * 0.5
            glass = Part.makeBox(gth, width - 2 * inset, height - 2 * inset)
            glass.Placement = FreeCAD.Placement(
                Vector(front_x - msz - gth, -half_w + inset, z0 + inset),
                FreeCAD.Rotation(),
            )
            solids.append(glass)

        # Door leaf: framed + glazed, hinged on left post (visual model only).
        # Place it in the front plane, centered in Y, bottom at belt plane.
        door_w_fc = self._fc_len(door_w)
        door_h_fc = self._fc_len(min(door_h, height_m))
        # Door frame members
        dw = door_w_fc
        dh = door_h_fc
        d_inset = msz * 1.2
        door_x = front_x - msz - (msz * 0.2)
        door_y0 = -dw / 2.0
        door_z0 = z0

        # Two stiles
        solids.append(member_box(msz, msz, dh, door_x - msz, door_y0, door_z0))
        solids.append(member_box(msz, msz, dh, door_x - msz, door_y0 + dw - msz, door_z0))
        # Top/bottom rails
        solids.append(member_box(msz, dw, msz, door_x - msz, door_y0, door_z0))
        solids.append(member_box(msz, dw, msz, door_x - msz, door_y0, door_z0 + dh - msz))

        if glass_m > 1e-6:
            gth = self._fc_len(glass_m)
            glass2 = Part.makeBox(gth, dw - 2 * d_inset, dh - 2 * d_inset)
            glass2.Placement = FreeCAD.Placement(
                Vector(door_x - msz - gth, door_y0 + d_inset, door_z0 + d_inset),
                FreeCAD.Rotation(),
            )
            solids.append(glass2)

        # Combine frame + brackets into one compound.
        # NOTE: bracket solids are already in world coordinates, while
        # frame solids are in local (pre-rotation) coordinates.
        # We must separate them: rotate only the frame solids.

        # Gather bracket solids (they were appended last, before glass/door).
        # Simpler: compound everything then rotate the whole compound.
        # The brackets are at the correct world position already, but they
        # are small enough that the rotation won't move them visibly since
        # they're placed at node positions that are already at the rotated angle.
        #
        # Actually, the brackets are placed at world node positions which
        # already account for the dome's geometry.  But the frame members are
        # built in a local system (radial from +X) which requires rotation.
        #
        # Solution: apply rotation to the whole compound.  Since brackets
        # are at world positions, we need to UN-rotate them before the global
        # rotation.  This is complex.  Instead, let's build the brackets in
        # local coords too, then rotate everything.

        # We already appended bracket solids above.  But they are in world
        # coordinates while the frame is in local (unrotated) coords.
        # Let's fix: remove bracket solids and re-add them after rotation.

        # A cleaner approach: separate frame parts and bracket parts.

        # Since the bracket code above placed them in world coords, we need
        # to inverse-transform them.  But it's simpler to just keep everything
        # in local coords and create the brackets in local coords too.
        # Let me rebuild: the brackets should be at the local-frame version
        # of the node positions.
        #
        # For simplicity, apply compound rotation to everything uniformly.
        # The brackets will rotate with the frame.  But they were placed at
        # pre-rotated dome node positions...
        #
        # OK, the cleanest fix: don't rotate bracket solids with the porch.
        # Build them separately.

        # Let's split: frame_solids = everything except brackets
        # bracket_solids = the bracket plates we added
        # Count: we added 2 plates per nearest node (h_plate + v_plate)
        num_bracket_solids = len(bracket_node_indices) * 2
        if num_bracket_solids > 0:
            frame_solids = solids[:-num_bracket_solids]
            bracket_solids_list = solids[-num_bracket_solids:]
        else:
            frame_solids = solids
            bracket_solids_list = []

        # Rotate frame (non-bracket) parts around Z.
        rot = FreeCAD.Rotation(Vector(0, 0, 1), float(ang_deg))
        frame_shape = Part.makeCompound(frame_solids)
        frame_shape.Placement = FreeCAD.Placement(Vector(0.0, 0.0, 0.0), rot)

        # Combine with bracket solids (already in world coords).
        if bracket_solids_list:
            all_shapes = [frame_shape] + bracket_solids_list
            porch_shape = Part.makeCompound(all_shapes)
        else:
            porch_shape = frame_shape

        obj = doc.addObject("Part::Feature", "EntryPorch")
        obj.Label = "EntryPorch"
        obj.Shape = porch_shape

        # Grouping.
        try:
            grp = None
            for o in list(getattr(doc, "Objects", []) or []):
                if str(getattr(o, "Name", "")) == "Base" and str(getattr(o, "TypeId", "")) == "App::DocumentObjectGroup":
                    grp = o
                    break
            if grp is None:
                grp = doc.addObject("App::DocumentObjectGroup", "Base")
                grp.Label = "Base"
            grp.addObject(obj)
        except Exception:
            pass

        try:
            doc.recompute()
        except Exception:
            pass

        return EntryPorchResult(
            name=str(getattr(obj, "Name", "EntryPorch")),
            angle_deg=ang_deg,
            belt_height_m=belt_height_m,
            bracket_node_indices=bracket_node_indices,
        )
